//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        public long ApplicantId { get; set; }
        public string FullName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public Nullable<long> MaritalStatus { get; set; }
        public string CNIC { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string MobileNo { get; set; }
        public string ConatctInfo { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string ShortSummary { get; set; }
        public string CoveringLetter { get; set; }
        public string Resume { get; set; }
        public Nullable<long> NoYearsOfExperience { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<long> LookQualificationId { get; set; }
        public string HRRemarks { get; set; }
        public string ApplicantRemarks { get; set; }
        public Nullable<long> LookOrganizationId { get; set; }
        public string ReferenceName { get; set; }
        public string ReferenceEmail { get; set; }
        public Nullable<System.DateTime> ExpectedDateOfJoining { get; set; }
        public Nullable<long> LookEmployeeTypeId { get; set; }
        public Nullable<long> LookDepartmentId { get; set; }
        public Nullable<long> LookDesignationId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<long> LookApplicantStatusId { get; set; }
        public Nullable<long> SelectionGrade { get; set; }
    }
}
