//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BioMetricInfo
    {
        public long BioMetricInfoId { get; set; }
        public Nullable<int> ProductSaleProfileId { get; set; }
        public string BioMetricSerialNo { get; set; }
        public string BioMetricDeviceBrand { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string IPAddress { get; set; }
        public Nullable<bool> IsPublicIp { get; set; }
    }
}
