//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeave
    {
        public long EmployeeLeaveId { get; set; }
        public Nullable<long> EmployeePolicyId { get; set; }
        public string PolicyName { get; set; }
        public string LeaveValue { get; set; }
        public long LookLeaveStatusId { get; set; }
        public System.DateTime LeaveDate { get; set; }
        public long EmployeeId { get; set; }
        public string PolicyUnit { get; set; }
        public Nullable<long> Year { get; set; }
        public Nullable<long> LookPolicyId { get; set; }
        public Nullable<long> EmployeeLeaveSummaryId { get; set; }
        public Nullable<long> LookLeaveRequestStatusId { get; set; }
        public Nullable<System.DateTime> LookLeaveRequestDate { get; set; }
        public Nullable<long> LeaveApprovedById { get; set; }
        public Nullable<System.DateTime> LeaveApprovedDate { get; set; }
    }
}
