//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeExperienceHistory
    {
        public long EmployeeExperienceHistoryId { get; set; }
        public long EmployeeId { get; set; }
        public Nullable<long> LookOrganizationId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string JobTitle { get; set; }
        public string JobDescription { get; set; }
        public Nullable<long> LookCityId { get; set; }
        public Nullable<long> LookCountryId { get; set; }
        public Nullable<double> Salary { get; set; }
    }
}
