//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLog
    {
        public long EmployeeLogId { get; set; }
        public long EmployeeId { get; set; }
        public string FullName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string FatherName { get; set; }
        public string HusbandName { get; set; }
        public string Gender { get; set; }
        public Nullable<long> MaritalStatus { get; set; }
        public string CNIC { get; set; }
        public bool IsDisable { get; set; }
        public string DisableDetail { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string MobileNo { get; set; }
        public string ConatctInfo { get; set; }
        public string ICEContactInfo { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string ShortSummary { get; set; }
        public string HRRemarks { get; set; }
        public Nullable<long> NoYearsOfExperience { get; set; }
        public Nullable<double> StartSalary { get; set; }
        public string ReferenceName { get; set; }
        public string ReferenceEmail { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public Nullable<long> ManagerId { get; set; }
        public Nullable<long> LookEmployeeTypeId { get; set; }
        public Nullable<long> LookDepartmentId { get; set; }
        public Nullable<long> LookDesignationId { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> UpdatedBy { get; set; }
        public Nullable<System.DateTime> LogCreateDate { get; set; }
        public Nullable<long> LogCeatedBy { get; set; }
    }
}
