//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeaveSummary
    {
        public long EmployeeLeaveSummaryId { get; set; }
        public long EmployeePolicyId { get; set; }
        public System.DateTime StartLeaveDate { get; set; }
        public System.DateTime EndLeaveDate { get; set; }
        public Nullable<long> ShortLeaves { get; set; }
        public Nullable<long> HalfLeaves { get; set; }
        public Nullable<long> Leaves { get; set; }
        public long EmployeeId { get; set; }
        public Nullable<long> LookLeaveStatusId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public System.DateTime StatusUpdateDate { get; set; }
    }
}
