//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAppliedLeave
    {
        public long EmployeeAppliedLeaveId { get; set; }
        public long EmployeeId { get; set; }
        public Nullable<System.DateTime> LeaveTimeStart { get; set; }
        public Nullable<System.DateTime> LaveTimeEnd { get; set; }
        public Nullable<System.DateTime> ActualTimeIn { get; set; }
        public Nullable<System.DateTime> ActualTimOut { get; set; }
        public long Status { get; set; }
        public Nullable<long> LookPolicyId { get; set; }
        public Nullable<System.DateTime> ForDate { get; set; }
        public string Reason { get; set; }
        public string HRRemarks { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
