//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.HRMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRMSdb : DbContext
    {
        public HRMSdb()
            : base("name=HRMSdb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applicant> Applicants { get; set; }
        public virtual DbSet<ApplicantAttachment> ApplicantAttachments { get; set; }
        public virtual DbSet<ApplicantInterview> ApplicantInterviews { get; set; }
        public virtual DbSet<ApplicantStatusChange> ApplicantStatusChanges { get; set; }
        public virtual DbSet<BioMetricData> BioMetricDatas { get; set; }
        public virtual DbSet<BiometricSchedule> BiometricSchedules { get; set; }
        public virtual DbSet<BiometricSync> BiometricSyncs { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeAppliedLeave> EmployeeAppliedLeaves { get; set; }
        public virtual DbSet<EmployeeAttachment> EmployeeAttachments { get; set; }
        public virtual DbSet<EmployeeAttendance> EmployeeAttendances { get; set; }
        public virtual DbSet<EmployeeEducation> EmployeeEducations { get; set; }
        public virtual DbSet<EmployeeExperienceHistory> EmployeeExperienceHistories { get; set; }
        public virtual DbSet<EmployeeLeave> EmployeeLeaves { get; set; }
        public virtual DbSet<EmployeeLeaveStatusHistory> EmployeeLeaveStatusHistories { get; set; }
        public virtual DbSet<EmployeeLeaveSummary> EmployeeLeaveSummaries { get; set; }
        public virtual DbSet<EmployeeLog> EmployeeLogs { get; set; }
        public virtual DbSet<EmployeePolicy> EmployeePolicies { get; set; }
        public virtual DbSet<EmployeesDependent> EmployeesDependents { get; set; }
        public virtual DbSet<EventLog> EventLogs { get; set; }
        public virtual DbSet<HRPolicy> HRPolicies { get; set; }
        public virtual DbSet<HRPolicyByCaption> HRPolicyByCaptions { get; set; }
        public virtual DbSet<HRPolicyCaption> HRPolicyCaptions { get; set; }
        public virtual DbSet<HRRecruitmentProcess> HRRecruitmentProcesses { get; set; }
        public virtual DbSet<LeftMenu> LeftMenus { get; set; }
        public virtual DbSet<LogInHistory> LogInHistories { get; set; }
        public virtual DbSet<LookBranch> LookBranches { get; set; }
        public virtual DbSet<LookBranchType> LookBranchTypes { get; set; }
        public virtual DbSet<LookCity> LookCities { get; set; }
        public virtual DbSet<LookCountry> LookCountries { get; set; }
        public virtual DbSet<LookDepartment> LookDepartments { get; set; }
        public virtual DbSet<LookDesignation> LookDesignations { get; set; }
        public virtual DbSet<LookEmployeeType> LookEmployeeTypes { get; set; }
        public virtual DbSet<LookGender> LookGenders { get; set; }
        public virtual DbSet<LookGrade> LookGrades { get; set; }
        public virtual DbSet<LookInstitution> LookInstitutions { get; set; }
        public virtual DbSet<LookJobType> LookJobTypes { get; set; }
        public virtual DbSet<LookLeaveStatu> LookLeaveStatus { get; set; }
        public virtual DbSet<LookOrganization> LookOrganizations { get; set; }
        public virtual DbSet<LookPayRollStatu> LookPayRollStatus { get; set; }
        public virtual DbSet<LookPolicy> LookPolicies { get; set; }
        public virtual DbSet<LookPolicyGroup> LookPolicyGroups { get; set; }
        public virtual DbSet<LookQualification> LookQualifications { get; set; }
        public virtual DbSet<LookQualificationType> LookQualificationTypes { get; set; }
        public virtual DbSet<LookSelectionProcess> LookSelectionProcesses { get; set; }
        public virtual DbSet<PayRoll> PayRolls { get; set; }
        public virtual DbSet<PayRollDetail> PayRollDetails { get; set; }
        public virtual DbSet<PayRollSummary> PayRollSummaries { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<ProductSaleProfile> ProductSaleProfiles { get; set; }
        public virtual DbSet<PublicHoliday> PublicHolidays { get; set; }
        public virtual DbSet<Recruitment> Recruitments { get; set; }
        public virtual DbSet<RecruitmentApproval> RecruitmentApprovals { get; set; }
        public virtual DbSet<RoleMenu> RoleMenus { get; set; }
        public virtual DbSet<RolePermission> RolePermissions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<ShiftSetting> ShiftSettings { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<BioMetricInfo> BioMetricInfoes { get; set; }
    }
}
