//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRPolicyByCaption
    {
        public long HRPolicyByCaptionId { get; set; }
        public int HRPolicyCaptionId { get; set; }
        public string HRPolicyCaption { get; set; }
        public long LookPolicyId { get; set; }
        public string PolicyValue { get; set; }
        public long GroupTypeId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public string PolicyName { get; set; }
        public Nullable<long> LookPolicyGroupId { get; set; }
        public Nullable<System.TimeSpan> TimeIn { get; set; }
        public Nullable<System.TimeSpan> TimeOut { get; set; }
        public Nullable<int> ProductSaleProfileId { get; set; }
        public long LookOrganizationId { get; set; }
    }
}
