//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRPolicyCaption
    {
        public int HRPolicyCaptionId { get; set; }
        public string PolicyCaption { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<bool> IsVariableTiming { get; set; }
        public Nullable<int> ProductSaleProfileId { get; set; }
    }
}
