//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRPolicy
    {
        public long HRPolicyId { get; set; }
        public long LookDesignationId { get; set; }
        public long LookPolicyId { get; set; }
        public string PolicyValue { get; set; }
        public long GroupTypeId { get; set; }
        public Nullable<int> ProductSaleProfileId { get; set; }
    }
}
