//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRRecruitmentProcess
    {
        public long HRRecruitmentProcessId { get; set; }
        public Nullable<long> ProcessId { get; set; }
        public Nullable<long> RecruitmentId { get; set; }
    }
}
