//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookBranch
    {
        public long LookBranchId { get; set; }
        public string BranchName { get; set; }
        public Nullable<long> LookBranchTypeId { get; set; }
        public Nullable<long> ParentBranchId { get; set; }
    }
}
