//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookPolicy
    {
        public long LookPolicyId { get; set; }
        public string PolicyName { get; set; }
        public string PolicyUnit { get; set; }
        public int LookPolicyGroupId { get; set; }
        public Nullable<int> ValueType { get; set; }
        public Nullable<bool> IsPercentage { get; set; }
    }
}
