//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayRoll
    {
        public long PayRollId { get; set; }
        public long EmployeeId { get; set; }
        public long MonthNumber { get; set; }
        public long YearNumber { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<decimal> GrossPay { get; set; }
        public Nullable<decimal> NetPay { get; set; }
        public Nullable<decimal> IncomeTax { get; set; }
        public Nullable<long> WorkingDaysRequired { get; set; }
        public Nullable<long> PublicHolidays { get; set; }
        public Nullable<long> Leaves { get; set; }
        public Nullable<long> Absents { get; set; }
        public Nullable<long> Attendance { get; set; }
        public Nullable<long> TotalHoursRequired { get; set; }
        public Nullable<long> TotalHours { get; set; }
        public Nullable<long> LookPayRollStatusId { get; set; }
        public Nullable<long> StatusUpdatedBy { get; set; }
        public Nullable<System.DateTime> StatusUpdateDate { get; set; }
    }
}
