//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public long PermissionId { get; set; }
        public bool IsActive { get; set; }
        public string Attribute { get; set; }
        public string Name { get; set; }
        public Nullable<long> MenuId { get; set; }
        public Nullable<long> LookDepartmentId { get; set; }
        public int PermissionLevel { get; set; }
    }
}
