//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecruitmentApproval
    {
        public long RecruitmentApprovalId { get; set; }
        public long RecruitmentId { get; set; }
        public long EmployeeId { get; set; }
        public System.DateTime ApprovedDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> ForwardToEmployeeId { get; set; }
        public Nullable<long> LookRecruitmentStatusId { get; set; }
    }
}
