//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleMenu
    {
        public long RoleMenuId { get; set; }
        public long MenuId { get; set; }
        public long RoleId { get; set; }
        public string DefaultControllerName { get; set; }
        public string DefaultActionName { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> ProductSaleProfileId { get; set; }
    }
}
